### ISSUE TITLE
BOM calls for 2x08 connector but PCB only has 2x06

### ISSUE THREAD

**Issue by diggles4** [m4x10187/Modxo_RP2040_Zero_Adapter#1]
Hello! I was collecting everything I needed for this build and noticed this discrepancy. Is only a 2x06 needed instead, or is the PCB missing holes?

**Comment by m4x10187** [comment]
You could go with a 2x06 if you like or a 2x08. I haven't done Xbox chips in a while, so if the 2x08 socket doesn't fit, you could always try going lower so that it fits through the holes.

**Comment by diggles4** [comment]
Update: used a 2x06 and it worked perfectly!
